[package]
name = "cbc-kms"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
aws-config = "1.1.7"
aws-sdk-kms = "1.17.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
cbc-core = { path = "../cbc-core" }
thiserror = "1.0"
async-trait = "0.1"
